# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Terminal"
license = "SimPL-2.0"
licenselink = "https://raw.githubusercontent.com/spf13/hugo/master/LICENSE.md"
description = "A simple theme that looks like an old IBM terminal"
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Sage"
  homepage = "https://twitter.com/SageHack"
